import type { TraceStep } from '@/lib/types'
import { ALGO_MAP } from '@/lib/algorithms'

type AlgorithmCodeSample = {
  language: 'cpp' | 'python' | 'javascript' | 'typescript' | 'text'
  code: string
  lineMap: Record<string, number>
}

const FALLBACK_SAMPLE: AlgorithmCodeSample = {
  language: 'text',
  code: [
    'read input and initialize state',
    'repeat core operation over structure',
    'update candidates / data structure',
    'emit final answer',
  ].join('\n'),
  lineMap: {
    compare: 2,
    swap: 2,
    assign: 3,
    merge: 3,
    visit_node: 2,
    enqueue: 3,
    relax_edge: 3,
    done: 4,
  },
}

const VISUALIZER_FALLBACKS: Record<string, AlgorithmCodeSample> = {
  sorting: {
    language: 'cpp',
    code: [
      'for (int i = 0; i < n; ++i) {',
      '  select active index / pivot / bucket;',
      '  compare and rearrange values;',
      '}',
      'return sorted array;',
    ].join('\n'),
    lineMap: { compare: 3, swap: 3, assign: 3, merge: 3, pivot: 2, sorted: 5, done: 5 },
  },
  graph: {
    language: 'cpp',
    code: [
      'init visited/dist/parent arrays;',
      'push source into queue/heap/stack;',
      'while (worklist not empty) {',
      '  pop current and explore outgoing edges;',
      '  relax/update neighbor state;',
      '}',
      'finalize traversal / shortest paths;',
    ].join('\n'),
    lineMap: {
      visit_node: 4,
      enqueue: 2,
      explore_edge: 4,
      consider_neighbor: 4,
      relax_edge: 5,
      finalize_node: 7,
      done: 7,
    },
  },
  recursion: {
    language: 'cpp',
    code: [
      'solve(problem) {',
      '  if (base_case) return;',
      '  choose candidate;',
      '  recurse on reduced problem;',
      '  backtrack if needed;',
      '}',
    ].join('\n'),
    lineMap: { call: 4, assign: 3, compare: 2, backtrack: 5, done: 6 },
  },
  dp: {
    language: 'cpp',
    code: [
      'initialize DP table;',
      'for each state i,j:',
      '  transition from previous states;',
      '  store best value;',
      'reconstruct answer if required;',
    ].join('\n'),
    lineMap: { init: 1, fill: 3, fill_cell: 3, depend: 3, assign: 4, done: 5 },
  },
  nqueens: {
    language: 'cpp',
    code: [
      'place(row) {',
      '  for each col in board:',
      '    if safe(row,col):',
      '      put queen and recurse;',
      '      remove queen (backtrack);',
      '}',
    ].join('\n'),
    lineMap: { compare: 3, assign: 4, backtrack: 5, done: 6 },
  },
  hash: {
    language: 'cpp',
    code: [
      'idx = hash(key) % table_size;',
      'while (slot occupied and key mismatch) {',
      '  probe/chain to next candidate slot;',
      '}',
      'insert/update key in resolved slot;',
    ].join('\n'),
    lineMap: { compare: 2, probe: 3, assign: 5, done: 5 },
  },
  string: {
    language: 'cpp',
    code: [
      'for each alignment/text index i:',
      '  compare pattern characters;',
      '  on mismatch, shift using rule (naive/LPS/hash);',
      '  on full match, report occurrence;',
    ].join('\n'),
    lineMap: { compare: 2, assign: 3, match: 4, done: 4 },
  },
  huffman: {
    language: 'cpp',
    code: [
      'build min-heap from character frequencies;',
      'while (heap size > 1) {',
      '  extract two minimum nodes;',
      '  merge and push combined node;',
      '}',
      'traverse tree to emit prefix codes;',
    ].join('\n'),
    lineMap: { compare: 3, merge: 4, assign: 4, done: 6 },
  },
  activity: {
    language: 'cpp',
    code: [
      'sort activities/jobs by greedy key;',
      'for each candidate in sorted order:',
      '  if feasible, pick and update state;',
      'return selected schedule;',
    ].join('\n'),
    lineMap: { compare: 3, assign: 3, done: 4 },
  },
  knapsack: {
    language: 'cpp',
    code: [
      'sort items by value/weight ratio;',
      'for each item:',
      '  take full or fractional amount if capacity allows;',
      '  update remaining capacity and value;',
      'return total value;',
    ].join('\n'),
    lineMap: { compare: 2, assign: 4, done: 5 },
  },
}

const SAMPLES: Record<string, AlgorithmCodeSample> = {
  bubblesort: {
    language: 'cpp',
    code: [
      'for (int i = 0; i < n - 1; ++i) {',
      '  for (int j = 0; j < n - i - 1; ++j) {',
      '    if (a[j] > a[j + 1]) {',
      '      swap(a[j], a[j + 1]);',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: {
      compare: 3,
      swap: 4,
      sorted: 6,
      done: 7,
    },
  },
  quicksort: {
    language: 'cpp',
    code: [
      'int partition(vector<int>& a, int lo, int hi) {',
      '  int pivot = a[hi];',
      '  int i = lo - 1;',
      '  for (int j = lo; j < hi; ++j) {',
      '    if (a[j] <= pivot) {',
      '      ++i; swap(a[i], a[j]);',
      '    }',
      '  }',
      '  swap(a[i + 1], a[hi]);',
      '  return i + 1;',
      '}',
    ].join('\n'),
    lineMap: {
      pivot: 2,
      compare: 5,
      swap: 6,
      assign: 6,
      done: 10,
    },
  },
  mergesort: {
    language: 'cpp',
    code: [
      'void mergeSort(vector<int>& a, int l, int r) {',
      '  if (l >= r) return;',
      '  int m = l + (r - l) / 2;',
      '  mergeSort(a, l, m);',
      '  mergeSort(a, m + 1, r);',
      '  merge(a, l, m, r);',
      '}',
    ].join('\n'),
    lineMap: {
      compare: 6,
      merge: 6,
      assign: 6,
      done: 7,
    },
  },
  countingsort: {
    language: 'cpp',
    code: [
      'int minVal = *min_element(a.begin(), a.end());',
      'int maxVal = *max_element(a.begin(), a.end());',
      'vector<int> count(maxVal - minVal + 1, 0);',
      'for (int x : a) count[x - minVal]++;',
      'for (int i = 1; i < count.size(); ++i) count[i] += count[i - 1];',
      'for (int i = n - 1; i >= 0; --i) out[--count[a[i] - minVal]] = a[i];',
      'a = out;',
    ].join('\n'),
    lineMap: {
      compare: 4,
      assign: 6,
      sorted: 7,
      done: 7,
    },
  },
  binarysearch: {
    language: 'cpp',
    code: [
      'int binarySearch(vector<int>& a, int target) {',
      '  int lo = 0, hi = a.size() - 1;',
      '  while (lo <= hi) {',
      '    int mid = lo + (hi - lo) / 2;',
      '    if (a[mid] == target) return mid;',
      '    if (a[mid] < target) lo = mid + 1;',
      '    else hi = mid - 1;',
      '  }',
      '  return -1;',
      '}',
    ].join('\n'),
    lineMap: {
      compare: 5,
      current: 4,
      done: 9,
    },
  },
  lcs: {
    language: 'cpp',
    code: [
      'for (int i = 0; i <= m; ++i) dp[i][0] = 0;',
      'for (int j = 0; j <= n; ++j) dp[0][j] = 0;',
      'for (int i = 1; i <= m; ++i) {',
      '  for (int j = 1; j <= n; ++j) {',
      '    if (a[i-1] == b[j-1])',
      '      dp[i][j] = dp[i-1][j-1] + 1;',
      '    else',
      '      dp[i][j] = max(dp[i-1][j], dp[i][j-1]);',
      '  }',
      '}',
      '// backtrack to reconstruct LCS',
    ].join('\n'),
    lineMap: { init: 1, fill_cell: 5, fill: 6, depend: 8, backtrack: 11, done: 11 },
  },
  knapsack01: {
    language: 'cpp',
    code: [
      'int knapsack(int W, int wt[], int val[], int n) {',
      '  int dp[n+1][W+1];',
      '  for (int i = 0; i <= n; i++) {',
      '    for (int w = 0; w <= W; w++) {',
      '      if (i == 0 || w == 0)',
      '        dp[i][w] = 0;',
      '      else if (wt[i-1] <= w)',
      '        dp[i][w] = max(',
      '          val[i-1] + dp[i-1][w - wt[i-1]],',
      '          dp[i-1][w]);',
      '      else',
      '        dp[i][w] = dp[i-1][w];',
      '    }',
      '  }',
      '  return dp[n][W];',
      '}',
    ].join('\n'),
    lineMap: { init: 2, fill_cell: 8, fill: 8, depend: 9, assign: 10, backtrack: 15, done: 16 },
  },
  fractionalknapsack: {
    language: 'cpp',
    code: [
      'double fractionalKnapsack(int W, Item items[], int n) {',
      '  sort(items, items+n, [](Item& a, Item& b) {',
      '    return (double)a.val/a.wt > (double)b.val/b.wt;',
      '  });',
      '  double totalValue = 0;',
      '  int remaining = W;',
      '  for (int i = 0; i < n; i++) {',
      '    if (remaining == 0) break;',
      '    int take = min(items[i].wt, remaining);',
      '    double fraction = (double)take / items[i].wt;',
      '    totalValue += fraction * items[i].val;',
      '    remaining -= take;',
      '  }',
      '  return totalValue;',
      '}',
    ].join('\n'),
    lineMap: { consider_item: 7, include: 11, partial_include: 10, exclude: 8, done: 14 },
  },
  insertionsort: {
    language: 'cpp',
    code: [
      'void insertionSort(int a[], int n) {',
      '  for (int i = 1; i < n; ++i) {',
      '    int key = a[i];',
      '    int j = i - 1;',
      '    while (j >= 0 && a[j] > key) {',
      '      a[j + 1] = a[j];',
      '      j--;',
      '    }',
      '    a[j + 1] = key;',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { compare: 5, swap: 6, assign: 9, done: 11 },
  },
  selectionsort: {
    language: 'cpp',
    code: [
      'void selectionSort(int a[], int n) {',
      '  for (int i = 0; i < n - 1; i++) {',
      '    int minIdx = i;',
      '    for (int j = i + 1; j < n; j++) {',
      '      if (a[j] < a[minIdx])',
      '        minIdx = j;',
      '    }',
      '    swap(a[i], a[minIdx]);',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { compare: 5, swap: 8, assign: 6, sorted: 9, done: 10 },
  },
  heapsort: {
    language: 'cpp',
    code: [
      'void heapify(int a[], int n, int i) {',
      '  int largest = i, l = 2*i+1, r = 2*i+2;',
      '  if (l < n && a[l] > a[largest]) largest = l;',
      '  if (r < n && a[r] > a[largest]) largest = r;',
      '  if (largest != i) {',
      '    swap(a[i], a[largest]);',
      '    heapify(a, n, largest);',
      '  }',
      '}',
      'void heapSort(int a[], int n) {',
      '  for (int i = n/2-1; i >= 0; i--) heapify(a,n,i);',
      '  for (int i = n-1; i > 0; i--) {',
      '    swap(a[0], a[i]);',
      '    heapify(a, i, 0);',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { compare: 3, swap: 6, assign: 6, sorted: 15, done: 16 },
  },
  dijkstra: {
    language: 'cpp',
    code: [
      'void dijkstra(int graph[][V], int src) {',
      '  int dist[V]; bool visited[V];',
      '  fill(dist, dist+V, INT_MAX);',
      '  dist[src] = 0;',
      '  priority_queue<pii, vector<pii>, greater<>> pq;',
      '  pq.push({0, src});',
      '  while (!pq.empty()) {',
      '    auto [d, u] = pq.top(); pq.pop();',
      '    if (visited[u]) continue;',
      '    visited[u] = true;',
      '    for (auto [v, w] : adj[u]) {',
      '      if (dist[u] + w < dist[v]) {',
      '        dist[v] = dist[u] + w;',
      '        pq.push({dist[v], v});',
      '      }',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { visit_node: 10, enqueue: 6, explore_edge: 11, relax_edge: 13, consider_neighbor: 12, finalize_node: 10, done: 18 },
  },
  bfs: {
    language: 'cpp',
    code: [
      'void bfs(int graph[][V], int src) {',
      '  bool visited[V] = {false};',
      '  queue<int> q;',
      '  visited[src] = true;',
      '  q.push(src);',
      '  while (!q.empty()) {',
      '    int u = q.front(); q.pop();',
      '    for (int v = 0; v < V; v++) {',
      '      if (graph[u][v] && !visited[v]) {',
      '        visited[v] = true;',
      '        q.push(v);',
      '      }',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { visit_node: 7, enqueue: 11, explore_edge: 9, consider_neighbor: 9, finalize_node: 7, done: 15 },
  },
  dfs: {
    language: 'cpp',
    code: [
      'void dfs(int graph[][V], int u, bool visited[]) {',
      '  visited[u] = true;',
      '  process(u);',
      '  for (int v = 0; v < V; v++) {',
      '    if (graph[u][v] && !visited[v]) {',
      '      dfs(graph, v, visited);',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { visit_node: 2, explore_edge: 5, consider_neighbor: 5, enqueue: 6, finalize_node: 2, done: 9 },
  },
  kmp: {
    language: 'cpp',
    code: [
      'void computeLPS(string pat, int lps[]) {',
      '  int len = 0, i = 1;',
      '  lps[0] = 0;',
      '  while (i < pat.size()) {',
      '    if (pat[i] == pat[len]) { lps[i++] = ++len; }',
      '    else if (len) { len = lps[len-1]; }',
      '    else { lps[i++] = 0; }',
      '  }',
      '}',
      'void kmpSearch(string text, string pat) {',
      '  int i = 0, j = 0;',
      '  while (i < text.size()) {',
      '    if (pat[j] == text[i]) { i++; j++; }',
      '    if (j == pat.size()) {',
      '      printf("Found at %d", i - j);',
      '      j = lps[j - 1];',
      '    } else if (i < text.size() && pat[j] != text[i]) {',
      '      if (j) j = lps[j-1];',
      '      else i++;',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { compare_char: 13, shift: 18, found: 15, done: 22 },
  },
  naivematch: {
    language: 'cpp',
    code: [
      'void naiveSearch(string text, string pat) {',
      '  int n = text.size(), m = pat.size();',
      '  for (int i = 0; i <= n - m; i++) {',
      '    int j;',
      '    for (j = 0; j < m; j++) {',
      '      if (text[i+j] != pat[j])',
      '        break;',
      '    }',
      '    if (j == m)',
      '      printf("Found at %d", i);',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { compare_char: 6, shift: 7, found: 10, done: 12 },
  },
  rabinkarp: {
    language: 'cpp',
    code: [
      'void rabinKarp(string text, string pat) {',
      '  int n = text.size(), m = pat.size();',
      '  int d = 256, q = 101;',
      '  int h = 1, p = 0, t = 0;',
      '  for (int i = 0; i < m-1; i++) h = (h*d) % q;',
      '  for (int i = 0; i < m; i++) {',
      '    p = (d*p + pat[i]) % q;',
      '    t = (d*t + text[i]) % q;',
      '  }',
      '  for (int i = 0; i <= n-m; i++) {',
      '    if (p == t) {',
      '      // verify char by char',
      '      bool match = true;',
      '      for (int j = 0; j < m; j++)',
      '        if (text[i+j] != pat[j]) { match=false; break; }',
      '      if (match) printf("Found at %d", i);',
      '    }',
      '    // slide window hash',
      '    if (i < n-m)',
      '      t = (d*(t - text[i]*h) + text[i+m]) % q;',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { hash_check: 11, compare_char: 15, found: 16, done: 22 },
  },
  nqueens: {
    language: 'cpp',
    code: [
      'bool isSafe(int board[][N], int row, int col) {',
      '  for (int i = 0; i < col; i++)',
      '    if (board[row][i]) return false;',
      '  for (int i=row,j=col; i>=0 && j>=0; i--,j--)',
      '    if (board[i][j]) return false;',
      '  for (int i=row,j=col; i<N && j>=0; i++,j--)',
      '    if (board[i][j]) return false;',
      '  return true;',
      '}',
      'bool solve(int board[][N], int col) {',
      '  if (col >= N) return true;',
      '  for (int i = 0; i < N; i++) {',
      '    if (isSafe(board, i, col)) {',
      '      board[i][col] = 1;',
      '      if (solve(board, col+1)) return true;',
      '      board[i][col] = 0; // backtrack',
      '    }',
      '  }',
      '  return false;',
      '}',
    ].join('\n'),
    lineMap: { compare: 13, assign: 14, backtrack: 16, done: 20 },
  },
  fibonacci: {
    language: 'cpp',
    code: [
      'int fib(int n) {',
      '  if (n <= 1) return n;',
      '  return fib(n - 1) + fib(n - 2);',
      '}',
    ].join('\n'),
    lineMap: { call: 3, compare: 2, assign: 3, done: 4 },
  },
  fibonaccidp: {
    language: 'cpp',
    code: [
      'int fibDP(int n) {',
      '  int dp[n + 1];',
      '  dp[0] = 0; dp[1] = 1;',
      '  for (int i = 2; i <= n; i++)',
      '    dp[i] = dp[i-1] + dp[i-2];',
      '  return dp[n];',
      '}',
    ].join('\n'),
    lineMap: { init: 3, fill_cell: 5, fill: 5, done: 7 },
  },
  subsetsum: {
    language: 'cpp',
    code: [
      'bool subsetSum(int set[], int n, int sum) {',
      '  bool dp[n+1][sum+1];',
      '  for (int i = 0; i <= n; i++) dp[i][0] = true;',
      '  for (int j = 1; j <= sum; j++) dp[0][j] = false;',
      '  for (int i = 1; i <= n; i++) {',
      '    for (int j = 1; j <= sum; j++) {',
      '      dp[i][j] = dp[i-1][j];',
      '      if (j >= set[i-1])',
      '        dp[i][j] = dp[i][j] || dp[i-1][j-set[i-1]];',
      '    }',
      '  }',
      '  return dp[n][sum];',
      '}',
    ].join('\n'),
    lineMap: { init: 3, fill_cell: 7, fill: 9, depend: 9, assign: 7, backtrack: 12, done: 13 },
  },
  lis: {
    language: 'cpp',
    code: [
      'int lis(int a[], int n) {',
      '  int dp[n];',
      '  fill(dp, dp+n, 1);',
      '  for (int i = 1; i < n; i++)',
      '    for (int j = 0; j < i; j++)',
      '      if (a[j] < a[i])',
      '        dp[i] = max(dp[i], dp[j]+1);',
      '  return *max_element(dp, dp+n);',
      '}',
    ].join('\n'),
    lineMap: { init: 3, fill_cell: 7, fill: 7, depend: 6, done: 9 },
  },
  matrixchain: {
    language: 'cpp',
    code: [
      'int matrixChain(int p[], int n) {',
      '  int dp[n][n];',
      '  for (int i = 1; i < n; i++) dp[i][i] = 0;',
      '  for (int len = 2; len < n; len++) {',
      '    for (int i = 1; i <= n-len; i++) {',
      '      int j = i + len - 1;',
      '      dp[i][j] = INT_MAX;',
      '      for (int k = i; k < j; k++) {',
      '        int cost = dp[i][k] + dp[k+1][j]',
      '                 + p[i-1]*p[k]*p[j];',
      '        dp[i][j] = min(dp[i][j], cost);',
      '      }',
      '    }',
      '  }',
      '  return dp[1][n-1];',
      '}',
    ].join('\n'),
    lineMap: { init: 3, fill_cell: 11, fill: 9, depend: 9, done: 16 },
  },
  bellmanford: {
    language: 'cpp',
    code: [
      'void bellmanFord(int V, Edge edges[], int E, int src) {',
      '  int dist[V];',
      '  fill(dist, dist+V, INT_MAX);',
      '  dist[src] = 0;',
      '  for (int i = 0; i < V-1; i++)',
      '    for (int j = 0; j < E; j++)',
      '      if (dist[edges[j].u] + edges[j].w < dist[edges[j].v])',
      '        dist[edges[j].v] = dist[edges[j].u] + edges[j].w;',
      '  // check negative cycles',
      '  for (int j = 0; j < E; j++)',
      '    if (dist[edges[j].u] + edges[j].w < dist[edges[j].v])',
      '      printf("Negative cycle!");',
      '}',
    ].join('\n'),
    lineMap: { visit_node: 5, explore_edge: 7, relax_edge: 8, finalize_node: 5, done: 13 },
  },
  kruskal: {
    language: 'cpp',
    code: [
      'void kruskal(Edge edges[], int V, int E) {',
      '  sort(edges, edges+E); // by weight',
      '  DisjointSet ds(V);',
      '  int mstWeight = 0;',
      '  for (int i = 0; i < E; i++) {',
      '    int u = edges[i].u, v = edges[i].v;',
      '    if (ds.find(u) != ds.find(v)) {',
      '      ds.merge(u, v);',
      '      mstWeight += edges[i].w;',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { visit_node: 6, explore_edge: 7, relax_edge: 8, finalize_node: 6, done: 12 },
  },
  prim: {
    language: 'cpp',
    code: [
      'void prim(int graph[][V]) {',
      '  int key[V]; bool inMST[V]; int parent[V];',
      '  fill(key, key+V, INT_MAX);',
      '  key[0] = 0; parent[0] = -1;',
      '  for (int count = 0; count < V; count++) {',
      '    int u = minKey(key, inMST);',
      '    inMST[u] = true;',
      '    for (int v = 0; v < V; v++)',
      '      if (graph[u][v] && !inMST[v]',
      '          && graph[u][v] < key[v]) {',
      '        parent[v] = u;',
      '        key[v] = graph[u][v];',
      '      }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { visit_node: 7, explore_edge: 9, relax_edge: 12, consider_neighbor: 9, finalize_node: 7, done: 15 },
  },
  huffman: {
    language: 'cpp',
    code: [
      'Node* buildHuffman(int freq[], int n) {',
      '  priority_queue<Node*, vector<Node*>, Cmp> pq;',
      '  for (int i = 0; i < n; i++)',
      '    pq.push(new Node(freq[i]));',
      '  while (pq.size() > 1) {',
      '    Node* left  = pq.top(); pq.pop();',
      '    Node* right = pq.top(); pq.pop();',
      '    Node* parent = new Node(left->freq + right->freq);',
      '    parent->left = left;',
      '    parent->right = right;',
      '    pq.push(parent);',
      '  }',
      '  return pq.top();',
      '}',
    ].join('\n'),
    lineMap: { compare: 6, merge: 8, assign: 11, done: 14 },
  },
  activityselection: {
    language: 'cpp',
    code: [
      'void activitySelection(Activity acts[], int n) {',
      '  sort(acts, acts+n, [](auto& a, auto& b) {',
      '    return a.finish < b.finish;',
      '  });',
      '  int lastFinish = acts[0].finish;',
      '  select(acts[0]);',
      '  for (int i = 1; i < n; i++) {',
      '    if (acts[i].start >= lastFinish) {',
      '      select(acts[i]);',
      '      lastFinish = acts[i].finish;',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    lineMap: { compare: 8, assign: 9, done: 13 },
  },
}

export function getAlgorithmCodeSample(algoId: string): AlgorithmCodeSample {
  const exact = SAMPLES[algoId]
  if (exact) return exact

  const visualizer = ALGO_MAP[algoId]?.visualizer
  if (visualizer && VISUALIZER_FALLBACKS[visualizer]) {
    return VISUALIZER_FALLBACKS[visualizer]
  }

  return FALLBACK_SAMPLE
}

export function getHighlightedLineForStep(algoId: string, step: TraceStep | undefined, currentStep: number): number {
  const sample = getAlgorithmCodeSample(algoId)
  if (!step) return 1

  if (step.op && sample.lineMap[step.op] != null) {
    return sample.lineMap[step.op]
  }

  // Fallback deterministic line pulse when op has no explicit map.
  const codeLines = sample.code.split('\n').length
  return 1 + (Math.max(0, currentStep) % Math.max(codeLines, 1))
}
